apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bert
  name: bert
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bert
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bert
    spec:
      containers:
      - image: gcr.io/your_registry/bert:dev
        imagePullPolicy: IfNotPresent
        name: bert-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
