apiVersion: v1
kind: Service
metadata:
  labels:
    app: bert
  name: bert-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9090
  selector:
    app: bert
